### ISSUE TITLE
test/level_2/list_of_map_test.go   Test_marshal_list_of_map case panic

### ISSUE THREAD

**Issue by chkpk** [thrift-iterator/go#6]
https://github.com/thrift-iterator/go/pull/5/commits/a64af9d49f11652e03fbffbee31a5fcc610b8b6a 这个commit可以修复这个panic，但是导致了其他test case panic....

```
=== RUN   Test_marshal_list_of_map
unexpected fault address 0x602be40
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x602be40 pc=0x580eda]

goroutine 9 [running]:
runtime.throw(0x99a3a6, 0x5)
	/home/ck/go/src/runtime/panic.go:616 +0x81 fp=0xc4200a19c0 sp=0xc4200a19a0 pc=0x5a3101
runtime.sigpanic()
	/home/ck/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc4200a1a10 sp=0xc4200a19c0 pc=0x5b9431
runtime.evacuated(...)
	/home/ck/go/src/runtime/hashmap.go:198
runtime.mapiternext(0xc4200c33e0)
	/home/ck/go/src/runtime/hashmap.go:771 +0x49a fp=0xc4200a1aa0 sp=0xc4200a1a10 pc=0x580eda
runtime.mapiterinit(0x922740, 0xc4200a56c0, 0xc4200c33e0)
	/home/ck/go/src/runtime/hashmap.go:737 +0x1f1 fp=0xc4200a1ac8 sp=0xc4200a1aa0 pc=0x580951
reflect.mapiterinit(0x922740, 0xc4200a56c0, 0x15)
	/home/ck/go/src/runtime/hashmap.go:1217 +0x54 fp=0xc4200a1af8 sp=0xc4200a1ac8 pc=0x582074
reflect.Value.MapKeys(0x922740, 0xc4200a56c0, 0x15, 0xc4200a56c0, 0x15, 0x5)
	/home/ck/go/src/reflect/value.go:1114 +0xdd fp=0xc4200a1ba0 sp=0xc4200a1af8 pc=0x62a54d
github.com/thrift-iterator/go/binding/reflection.(*mapEncoder).encode(0xc420179710, 0xc4200a56c0, 0x9ea0a0, 0xc4200e6460)
	/home/ck/work/src/github.com/thrift-iterator/go/binding/reflection/encode_map.go:21 +0x9f fp=0xc4200a1c60 sp=0xc4200a1ba0 pc=0x8a85ef
github.com/thrift-iterator/go/binding/reflection.(*sliceEncoder).encode(0xc420179740, 0xc42018e420, 0x9ea0a0, 0xc4200e6460)
	/home/ck/work/src/github.com/thrift-iterator/go/binding/reflection/encode_slice.go:21 +0xa3 fp=0xc4200a1ca0 sp=0xc4200a1c60 pc=0x8a8fc3
github.com/thrift-iterator/go/binding/reflection.(*valEncoderAdapter).Encode(0xc4200a56f0, 0x9020e0, 0xc42018e420, 0x9ea0a0, 0xc4200e6460)
	/home/ck/work/src/github.com/thrift-iterator/go/binding/reflection/unsafe.go:45 +0x51 fp=0xc4200a1cd0 sp=0xc4200a1ca0 pc=0x8a92c1
github.com/thrift-iterator/go.(*frozenConfig).Marshal(0xc42017ee40, 0x9020e0, 0xc42018e420, 0xc42018e460, 0x2, 0xc42018e440, 0x1, 0x2)
	/home/ck/work/src/github.com/thrift-iterator/go/config.go:258 +0x113 fp=0xc4200a1d60 sp=0xc4200a1cd0 pc=0x8b2b43
github.com/thrift-iterator/go/test.glob..func5(0x9020e0, 0xc42018e420, 0x9020e0, 0xc42018e420, 0xc42008fe01, 0x588cb8, 0x6607ed)
	/home/ck/work/src/github.com/thrift-iterator/go/test/combinations.go:35 +0x257 fp=0xc4200a1e40 sp=0xc4200a1d60 pc=0x8b54e7
command-line-arguments.Test_marshal_list_of_map(0xc4201805a0)
	/home/ck/work/src/github.com/thrift-iterator/go/test/level_2/list_of_map_test.go:98 +0x32c fp=0xc4200a1fa8 sp=0xc4200a1e40 pc=0x8bb22c
testing.tRunner(0xc4201805a0, 0x9b2cb0)
	/home/ck/go/src/testing/testing.go:777 +0xd0 fp=0xc4200a1fd0 sp=0xc4200a1fa8 pc=0x660890
runtime.goexit()
	/home/ck/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200a1fd8 sp=0xc4200a1fd0 pc=0x5d2781
created by testing.(*T).Run
	/home/ck/go/src/testing/testing.go:824 +0x2e0
```

**Comment by chkpk** [comment]
panic原因可能是  empty interface 中存储的是 hashmap 的地址，而非 map的地址
两者区别见 https://play.golang.org/p/iVY6Rf3bcp4
临时修复方式： https://github.com/thrift-iterator/go/pull/5/commits/3a867c5c62050e1b43845741492e6f0dfdc52f67
